# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(220, 283)
        MainWindow.setMinimumSize(QtCore.QSize(220, 263))
        MainWindow.setMaximumSize(QtCore.QSize(220, 283))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('comp_out/recursos/kake_icon2.ico'), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background: #282828;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(220, 263))
        self.centralwidget.setMaximumSize(QtCore.QSize(221, 264))
        self.centralwidget.setStyleSheet("color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 201, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.lineEdit_senha = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_senha.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.lineEdit_senha.setStyleSheet("border: 1px solid white;\n"
"border-radius: 5px;")
        self.lineEdit_senha.setMaxLength(50)
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.gridLayout.addWidget(self.lineEdit_senha, 2, 1, 1, 1)
        self.lineEdit_login = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_login.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.lineEdit_login.setStyleSheet("border: 1px solid white;\n"
"border-radius: 5px;")
        self.lineEdit_login.setMaxLength(15)
        self.lineEdit_login.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.gridLayout.addWidget(self.lineEdit_login, 1, 1, 1, 1)
        self.pushButton_conectar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_conectar.setGeometry(QtCore.QRect(50, 230, 131, 23))
        self.pushButton_conectar.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.pushButton_conectar.setAutoDefault(True)
        self.pushButton_conectar.setObjectName("pushButton_conectar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KL BOT - Login"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "Senha"))
        self.label_3.setText(_translate("MainWindow", "KL BOT"))
        self.pushButton_conectar.setText(_translate("MainWindow", "Conectar"))
